# Generated by Django 4.0.1 on 2022-01-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
